version: '3'
services:
  grantsdb:
    image: ghostffcode/grants-db:latest
    platform: linux/amd64
    container_name: grantsdb
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Grants
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - grantsdb
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sybilx@supermodular.xyz
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
  metabase:
    image: metabase/metabase:latest
    platform: linux/amd64
    container_name: metabase
    depends_on:
      - grantsdb
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: grantsdb
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped